name: atomcto_assignment
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite:
  intl: ^0.18.1
  skeletons: ^0.0.3
  flutter_bloc: ^8.1.3
  dropdown_button2: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/fonts/

  fonts:
   - family: roboto
     fonts:
       - asset: assets/fonts/roboto_regular.ttf